version: "3.9"

services:      
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django
      - certbot
    command: bash -c 'nginx -g "daemon off;"'
    volumes:
      - ./support/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/serve_content:/etc/nginx/html
      - ./support/logs:/etc/nginx/logs
      - ./support/sshkeys:/etc/letsencrypt
    links:
      - django

  certbot:
    image: certbot/certbot:latest

  django:
    build:
      context: .
      dockerfile: Dockerfile-django
    ports:
      - "8002:8002"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}