FROM python:3.10-bullseye AS backend-deps
WORKDIR /backend
COPY /backend/requirements.txt .
RUN apt-get update
RUN apt-get install -y libgdal-dev gdal-bin
RUN pip install GDAL==3.2.2.1
# RUN apt-get install libpq5 
RUN pip install geopandas
RUN pip install -r requirements.txt
RUN apt-get install libgl1-mesa-glx -y
RUN apt-get install lsof tmux -y

FROM backend-deps AS backend-built
WORKDIR /backend
COPY backend .

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]